### PR TITLE
Node.js Compatibility Fix

### PR DESCRIPTION
**Pull request by Arora-Sir**
Resolved Node.js v16.16.0 compatibility issue with simplified module import syntax.

### CODE REVIEW

**Comment by iietmoon** [comment]
Node.js has an incredible ecosystem of frameworks, and we’re contributing to that by building mavro — a fast, minimalistic, and scalable Node.js framework built on Koa and TypeScript. We’re actively contributing to Koa’s roadmap and shaping mavro to be the go-to framework for developers who value simplicity and performance. If you’re a Node.js enthusiast looking to contribute to exciting open-source projects, we’d love to collaborate! Let’s push the boundaries of backend development together! 👉 [Join our community on Discord](https://discord.gg/jJK5kZx84B)

**Comment by pivotiiii** [comment]
This is an issue with the "Open" module and should be brought up with them. Note that the version of Open this plugin uses has Node v18 as a minimum requirement.

**Comment by Arora-Sir** [comment]
> This is an issue with the "Open" module and should be brought up with them. Note that the version of Open this plugin uses has Node v18 as a minimum requirement. 

Yes, I know it's for v18, but I've done a fix for v16 too in case someone using v16 :)

**Comment by pivotiiii** [comment]
That is nice of you, but you cannot expect a user to dig through their file system for some random dependency and change some lines every time the plugin updates. Again, submit your fix to the Open module. Maybe they will merge it, at that point I can include it as well.

**Pull request closed without merging**
